#syntax=docker/dockerfile-upstream:latest

FROM hydra_ext as hydra-ext
FROM columnar_ext as columnar-ext

FROM spilobase

COPY --from=hydra-ext /pg_ext /
COPY --from=columnar-ext /pg_ext /
COPY files/all/postgres-appliance/scripts /scripts/

# Default envs
ENV PGVERSION=13 SPILO_PROVIDER=local PGUSER_SUPERUSER=postgres PGPASSWORD_SUPERUSER=hydra
